version: '3.3'
networks:
  mynetwork:
    external:
      name: test
services:
  app:
    build: ./
    image: app
    container_name: app
    ports:
      - "8888:8888"
    restart: always
    networks:
      - test
    
